version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AtlasURI=${MONGO_DB_CONNECTION_STRING}
    volumes:
      - .:/app